# Generated by Django 3.2.9 on 2022-10-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waybill',
            options={'ordering': ('price', 'created_at')},
        ),
    ]
